camera_frame    : "camera_link"
results_topic   : "results"
project_path    : find(ros_visual)
image_topic     : "/chroma_proc/image"
image_dif_topic : "/chroma_proc/image_dif"
csv_fields      : "Timestamp\tRect_id\tRect_x\tRect_y\tRect_W\tRect_H\tBox_Ratio\tBox_Ratio_diff\tDistance\tDistance_diff\tx_diff\tx_delta\ty_diff\ty_delta\ty_norm\ty_norm_diff\tZ_Diff\tZ_Diff_Norm\tDepth_Std"
min_depth       : 0
max_depth       : 8000
create_directory: true
write_csv       : true
