results_topic: "results"
project_path: find(ros_visual)
image_topic: "/chroma_proc/image"
image_dif_topic: "/chroma_proc/image_dif"
depth_topic: "/depth_proc/image"
playback_topics: false
write_csv: true
display: true
min_depth: 0
max_depth: 6000
camera_frame: "camera_link"
